"""
Stock market data configuration.

- market_cap_b: Market capitalization in billions of USD (4 decimal places)
- volume_m: Trading volume in millions of shares (2 decimal places)
- options: Whether options are available for this symbol

Sorted alphabetically by symbol. Duplicate symbols removed.
"""

STOCKS = [
    {
        "symbol": "AAPL",
        "name": "Apple Inc.",
        "market_cap_b": 4880.0000,
        "country": "United States",
        "volume_m": 30.04,
        "options": True,
    },
    {
        "symbol": "ABBV",
        "name": "AbbVie Inc.",
        "market_cap_b": 456.6500,
        "country": "United States",
        "volume_m": 2.73,
        "options": True,
    },
    {
        "symbol": "ABT",
        "name": "Abbott Laboratories",
        "market_cap_b": 182.5700,
        "country": "United States",
        "volume_m": 3.32,
        "options": True,
    },
    {
        "symbol": "ADBE",
        "name": "Adobe Inc.",
        "market_cap_b": 98.4100,
        "country": "United States",
        "volume_m": 4.07,
        "options": True,
    },
    {
        "symbol": "ADI",
        "name": "Analog Devices, Inc.",
        "market_cap_b": 178.2100,
        "country": "United States",
        "volume_m": 2.19,
        "options": True,
    },
    {
        "symbol": "ADP",
        "name": "Automatic Data Processing, Inc.",
        "market_cap_b": 103.7500,
        "country": "United States",
        "volume_m": 1.28,
        "options": True,
    },
    {
        "symbol": "AEP",
        "name": "American Electric Power Company, Inc.",
        "market_cap_b": 69.6600,
        "country": "United States",
        "volume_m": 2.93,
        "options": True,
    },
    {
        "symbol": "ALAB",
        "name": "Astera Labs, Inc.",
        "market_cap_b": 50.1300,
        "country": "United States",
        "volume_m": 2.95,
        "options": True,
    },
    {
        "symbol": "AMAT",
        "name": "Applied Materials, Inc.",
        "market_cap_b": 398.5000,
        "country": "United States",
        "volume_m": 6.22,
        "options": True,
    },
    {
        "symbol": "AMD",
        "name": "Advanced Micro Devices, Inc.",
        "market_cap_b": 796.1600,
        "country": "United States",
        "volume_m": 22.30,
        "options": True,
    },
    {
        "symbol": "AMT",
        "name": "American Tower Corporation",
        "market_cap_b": 81.1100,
        "country": "United States",
        "volume_m": 1.60,
        "options": True,
    },
    {
        "symbol": "AMZN",
        "name": "Amazon.com, Inc.",
        "market_cap_b": 2560.0000,
        "country": "United States",
        "volume_m": 41.04,
        "options": True,
    },
    {
        "symbol": "ANET",
        "name": "Arista Networks, Inc.",
        "market_cap_b": 212.5900,
        "country": "United States",
        "volume_m": 3.68,
        "options": True,
    },
    {
        "symbol": "APH",
        "name": "Amphenol Corporation",
        "market_cap_b": 193.6100,
        "country": "United States",
        "volume_m": 5.59,
        "options": True,
    },
    {
        "symbol": "APO",
        "name": "Apollo Global Management, Inc.",
        "market_cap_b": 69.4600,
        "country": "United States",
        "volume_m": 1.77,
        "options": True,
    },
    {
        "symbol": "APP",
        "name": "AppLovin Corporation",
        "market_cap_b": 136.0200,
        "country": "United States",
        "volume_m": 3.93,
        "options": True,
    },
    {
        "symbol": "AVGO",
        "name": "Broadcom Inc.",
        "market_cap_b": 1840.0000,
        "country": "United States",
        "volume_m": 10.75,
        "options": True,
    },
    {
        "symbol": "BA",
        "name": "The Boeing Company",
        "market_cap_b": 174.0500,
        "country": "United States",
        "volume_m": 2.54,
        "options": True,
    },
    {
        "symbol": "BAC",
        "name": "Bank of America Corporation",
        "market_cap_b": 434.0600,
        "country": "United States",
        "volume_m": 11.63,
        "options": True,
    },
    {
        "symbol": "BE",
        "name": "Bloom Energy Corporation",
        "market_cap_b": 60.8500,
        "country": "United States",
        "volume_m": 23.62,
        "options": True,
    },
    {
        "symbol": "BKNG",
        "name": "Booking Holdings Inc.",
        "market_cap_b": 149.2300,
        "country": "United States",
        "volume_m": 3.46,
        "options": True,
    },
    {
        "symbol": "BKR",
        "name": "Baker Hughes Company",
        "market_cap_b": 59.3100,
        "country": "United States",
        "volume_m": 3.67,
        "options": True,
    },
    {
        "symbol": "BMY",
        "name": "Bristol-Myers Squibb Company",
        "market_cap_b": 131.2500,
        "country": "United States",
        "volume_m": 10.03,
        "options": True,
    },
    {
        "symbol": "BRK.B",
        "name": "Berkshire Hathaway Inc.",
        "market_cap_b": 1100.0000,
        "country": "United States",
        "volume_m": 1.89,
        "options": True,
    },
    {
        "symbol": "BSX",
        "name": "Boston Scientific Corporation",
        "market_cap_b": 67.2400,
        "country": "United States",
        "volume_m": 10.82,
        "options": True,
    },
    {
        "symbol": "BX",
        "name": "Blackstone Inc.",
        "market_cap_b": 160.4400,
        "country": "United States",
        "volume_m": 2.51,
        "options": True,
    },
    {
        "symbol": "C",
        "name": "Citigroup Inc.",
        "market_cap_b": 221.3800,
        "country": "United States",
        "volume_m": 4.30,
        "options": True,
    },
    {
        "symbol": "CAT",
        "name": "Caterpillar Inc.",
        "market_cap_b": 371.8200,
        "country": "United States",
        "volume_m": 1.84,
        "options": True,
    },
    {
        "symbol": "CEG",
        "name": "Constellation Energy Corporation",
        "market_cap_b": 95.4700,
        "country": "United States",
        "volume_m": 1.42,
        "options": True,
    },
    {
        "symbol": "CI",
        "name": "The Cigna Group",
        "market_cap_b": 76.9900,
        "country": "United States",
        "volume_m": 1.10,
        "options": True,
    },
    {
        "symbol": "CIEN",
        "name": "Ciena Corporation",
        "market_cap_b": 51.7100,
        "country": "United States",
        "volume_m": 1.31,
        "options": True,
    },
    {
        "symbol": "CL",
        "name": "Colgate-Palmolive Company",
        "market_cap_b": 73.1300,
        "country": "United States",
        "volume_m": 1.91,
        "options": True,
    },
    {
        "symbol": "CMCSA",
        "name": "Comcast Corporation",
        "market_cap_b": 83.6100,
        "country": "United States",
        "volume_m": 12.47,
        "options": True,
    },
    {
        "symbol": "CME",
        "name": "CME Group Inc.",
        "market_cap_b": 95.4300,
        "country": "United States",
        "volume_m": 1.22,
        "options": True,
    },
    {
        "symbol": "COF",
        "name": "Capital One Financial Corporation",
        "market_cap_b": 128.2900,
        "country": "United States",
        "volume_m": 1.61,
        "options": True,
    },
    {
        "symbol": "COP",
        "name": "ConocoPhillips",
        "market_cap_b": 143.7100,
        "country": "United States",
        "volume_m": 2.33,
        "options": True,
    },
    {
        "symbol": "COST",
        "name": "Costco Wholesale Corporation",
        "market_cap_b": 422.2300,
        "country": "United States",
        "volume_m": 1.02,
        "options": True,
    },
    {
        "symbol": "CRM",
        "name": "Salesforce, Inc.",
        "market_cap_b": 147.3000,
        "country": "United States",
        "volume_m": 6.54,
        "options": True,
    },
    {
        "symbol": "CRWD",
        "name": "CrowdStrike Holdings, Inc.",
        "market_cap_b": 185.5200,
        "country": "United States",
        "volume_m": 4.18,
        "options": True,
    },
    {
        "symbol": "CSCO",
        "name": "Cisco Systems, Inc.",
        "market_cap_b": 446.5300,
        "country": "United States",
        "volume_m": 8.54,
        "options": True,
    },
    {
        "symbol": "CSX",
        "name": "CSX Corporation",
        "market_cap_b": 92.5300,
        "country": "United States",
        "volume_m": 5.02,
        "options": True,
    },
    {
        "symbol": "CTAS",
        "name": "Cintas Corporation",
        "market_cap_b": 82.8000,
        "country": "United States",
        "volume_m": 1.33,
        "options": True,
    },
    {
        "symbol": "CTVA",
        "name": "Corteva, Inc.",
        "market_cap_b": 59.9900,
        "country": "United States",
        "volume_m": 2.07,
        "options": True,
    },
    {
        "symbol": "CVNA",
        "name": "Carvana Co.",
        "market_cap_b": 65.1200,
        "country": "United States",
        "volume_m": 21.23,
        "options": True,
    },
    {
        "symbol": "CVS",
        "name": "CVS Health Corporation",
        "market_cap_b": 134.1500,
        "country": "United States",
        "volume_m": 3.44,
        "options": True,
    },
    {
        "symbol": "CVX",
        "name": "Chevron Corporation",
        "market_cap_b": 377.4700,
        "country": "United States",
        "volume_m": 2.89,
        "options": True,
    },
    {
        "symbol": "D",
        "name": "Dominion Energy, Inc.",
        "market_cap_b": 61.3100,
        "country": "United States",
        "volume_m": 1.31,
        "options": True,
    },
    {
        "symbol": "DAL",
        "name": "Delta Air Lines, Inc.",
        "market_cap_b": 57.8200,
        "country": "United States",
        "volume_m": 2.47,
        "options": True,
    },
    {
        "symbol": "DASH",
        "name": "DoorDash, Inc.",
        "market_cap_b": 84.2200,
        "country": "United States",
        "volume_m": 1.53,
        "options": True,
    },
    {
        "symbol": "DDOG",
        "name": "Datadog, Inc.",
        "market_cap_b": 95.0700,
        "country": "United States",
        "volume_m": 2.04,
        "options": True,
    },
    {
        "symbol": "DELL",
        "name": "Dell Technologies Inc.",
        "market_cap_b": 262.8800,
        "country": "United States",
        "volume_m": 3.56,
        "options": True,
    },
    {
        "symbol": "DHR",
        "name": "Danaher Corporation",
        "market_cap_b": 137.7600,
        "country": "United States",
        "volume_m": 2.30,
        "options": True,
    },
    {
        "symbol": "DIS",
        "name": "The Walt Disney Company",
        "market_cap_b": 166.6500,
        "country": "United States",
        "volume_m": 9.78,
        "options": True,
    },
    {
        "symbol": "DLR",
        "name": "Digital Realty Trust, Inc.",
        "market_cap_b": 73.0700,
        "country": "United States",
        "volume_m": 1.30,
        "options": True,
    },
    {
        "symbol": "DUK",
        "name": "Duke Energy Corporation",
        "market_cap_b": 98.5900,
        "country": "United States",
        "volume_m": 2.25,
        "options": True,
    },
    {
        "symbol": "DVN",
        "name": "Devon Energy Corporation",
        "market_cap_b": 50.5400,
        "country": "United States",
        "volume_m": 3.83,
        "options": True,
    },
    {
        "symbol": "EA",
        "name": "Electronic Arts Inc.",
        "market_cap_b": 52.5200,
        "country": "United States",
        "volume_m": 2.40,
        "options": True,
    },
    {
        "symbol": "EMR",
        "name": "Emerson Electric Co.",
        "market_cap_b": 83.7400,
        "country": "United States",
        "volume_m": 1.23,
        "options": True,
    },
    {
        "symbol": "EPD",
        "name": "Enterprise Products Partners L.P.",
        "market_cap_b": 82.5800,
        "country": "United States",
        "volume_m": 2.33,
        "options": True,
    },
    {
        "symbol": "ET",
        "name": "Energy Transfer LP",
        "market_cap_b": 69.5500,
        "country": "United States",
        "volume_m": 2.92,
        "options": True,
    },
    {
        "symbol": "F",
        "name": "Ford Motor Company",
        "market_cap_b": 58.9600,
        "country": "United States",
        "volume_m": 31.40,
        "options": True,
    },
    {
        "symbol": "FAST",
        "name": "Fastenal Company",
        "market_cap_b": 53.6800,
        "country": "United States",
        "volume_m": 3.14,
        "options": True,
    },
    {
        "symbol": "FCX",
        "name": "Freeport-McMoRan Inc.",
        "market_cap_b": 90.7000,
        "country": "United States",
        "volume_m": 6.92,
        "options": True,
    },
    {
        "symbol": "FITB",
        "name": "Fifth Third Bancorp",
        "market_cap_b": 51.5800,
        "country": "United States",
        "volume_m": 2.78,
        "options": True,
    },
    {
        "symbol": "FTNT",
        "name": "Fortinet, Inc.",
        "market_cap_b": 112.1400,
        "country": "United States",
        "volume_m": 5.88,
        "options": True,
    },
    {
        "symbol": "GE",
        "name": "GE Aerospace",
        "market_cap_b": 367.3300,
        "country": "United States",
        "volume_m": 1.16,
        "options": True,
    },
    {
        "symbol": "GEV",
        "name": "GE Vernova Inc.",
        "market_cap_b": 258.9900,
        "country": "United States",
        "volume_m": 1.81,
        "options": True,
    },
    {
        "symbol": "GILD",
        "name": "Gilead Sciences, Inc.",
        "market_cap_b": 161.2400,
        "country": "United States",
        "volume_m": 2.67,
        "options": True,
    },
    {
        "symbol": "GLW",
        "name": "Corning Incorporated",
        "market_cap_b": 121.9700,
        "country": "United States",
        "volume_m": 11.57,
        "options": True,
    },
    {
        "symbol": "GM",
        "name": "General Motors Company",
        "market_cap_b": 76.5600,
        "country": "United States",
        "volume_m": 2.89,
        "options": True,
    },
    {
        "symbol": "GOOG",
        "name": "Alphabet Inc.",
        "market_cap_b": 4110.0000,
        "country": "United States",
        "volume_m": 9.24,
        "options": True,
    },
    {
        "symbol": "GOOGL",
        "name": "Alphabet Inc.",
        "market_cap_b": 4080.0000,
        "country": "United States",
        "volume_m": 15.57,
        "options": True,
    },
    {
        "symbol": "GS",
        "name": "The Goldman Sachs Group, Inc.",
        "market_cap_b": 314.0900,
        "country": "United States",
        "volume_m": 1.33,
        "options": True,
    },
    {
        "symbol": "HD",
        "name": "The Home Depot, Inc.",
        "market_cap_b": 331.5900,
        "country": "United States",
        "volume_m": 1.68,
        "options": True,
    },
    {
        "symbol": "HOOD",
        "name": "Robinhood Markets, Inc.",
        "market_cap_b": 78.7900,
        "country": "United States",
        "volume_m": 19.23,
        "options": True,
    },
    {
        "symbol": "HPE",
        "name": "Hewlett Packard Enterprise Company",
        "market_cap_b": 61.8700,
        "country": "United States",
        "volume_m": 7.68,
        "options": True,
    },
    {
        "symbol": "IBM",
        "name": "International Business Machines Corporation",
        "market_cap_b": 209.7200,
        "country": "United States",
        "volume_m": 3.24,
        "options": True,
    },
    {
        "symbol": "ICE",
        "name": "Intercontinental Exchange, Inc.",
        "market_cap_b": 87.4500,
        "country": "United States",
        "volume_m": 3.68,
        "options": True,
    },
    {
        "symbol": "INTC",
        "name": "Intel Corporation",
        "market_cap_b": 466.6700,
        "country": "United States",
        "volume_m": 90.20,
        "options": True,
    },
    {
        "symbol": "INTU",
        "name": "Intuit Inc.",
        "market_cap_b": 84.9600,
        "country": "United States",
        "volume_m": 2.60,
        "options": True,
    },
    {
        "symbol": "ISRG",
        "name": "Intuitive Surgical, Inc.",
        "market_cap_b": 123.4000,
        "country": "United States",
        "volume_m": 1.25,
        "options": True,
    },
    {
        "symbol": "JNJ",
        "name": "Johnson & Johnson",
        "market_cap_b": 616.3100,
        "country": "United States",
        "volume_m": 4.03,
        "options": True,
    },
    {
        "symbol": "JPM",
        "name": "JPMorgan Chase & Co.",
        "market_cap_b": 934.9700,
        "country": "United States",
        "volume_m": 2.88,
        "options": True,
    },
    {
        "symbol": "KKR",
        "name": "KKR & Co. Inc.",
        "market_cap_b": 90.8200,
        "country": "United States",
        "volume_m": 2.18,
        "options": True,
    },
    {
        "symbol": "KLAC",
        "name": "KLA Corporation",
        "market_cap_b": 238.6800,
        "country": "United States",
        "volume_m": 7.07,
        "options": True,
    },
    {
        "symbol": "KMI",
        "name": "Kinder Morgan, Inc.",
        "market_cap_b": 70.0800,
        "country": "United States",
        "volume_m": 4.37,
        "options": True,
    },
    {
        "symbol": "KO",
        "name": "The Coca-Cola Company",
        "market_cap_b": 380.0800,
        "country": "United States",
        "volume_m": 8.30,
        "options": True,
    },
    {
        "symbol": "LITE",
        "name": "Lumentum Holdings Inc.",
        "market_cap_b": 53.2200,
        "country": "United States",
        "volume_m": 3.15,
        "options": True,
    },
    {
        "symbol": "LLY",
        "name": "Eli Lilly and Company",
        "market_cap_b": 1030.0000,
        "country": "United States",
        "volume_m": 1.48,
        "options": True,
    },
    {
        "symbol": "LRCX",
        "name": "Lam Research Corporation",
        "market_cap_b": 374.5100,
        "country": "United States",
        "volume_m": 12.04,
        "options": True,
    },
    {
        "symbol": "MA",
        "name": "Mastercard Incorporated",
        "market_cap_b": 512.6500,
        "country": "United States",
        "volume_m": 2.93,
        "options": True,
    },
    {
        "symbol": "MCD",
        "name": "McDonald's Corporation",
        "market_cap_b": 190.3700,
        "country": "United States",
        "volume_m": 1.67,
        "options": True,
    },
    {
        "symbol": "MDLN",
        "name": "Medline Inc.",
        "market_cap_b": 51.0900,
        "country": "United States",
        "volume_m": 1.03,
        "options": True,
    },
    {
        "symbol": "MDLZ",
        "name": "Mondelez International, Inc.",
        "market_cap_b": 80.2500,
        "country": "United States",
        "volume_m": 4.24,
        "options": True,
    },
    {
        "symbol": "MET",
        "name": "MetLife, Inc.",
        "market_cap_b": 62.4500,
        "country": "United States",
        "volume_m": 2.70,
        "options": True,
    },
    {
        "symbol": "META",
        "name": "Meta Platforms, Inc.",
        "market_cap_b": 1350.0000,
        "country": "United States",
        "volume_m": 27.72,
        "options": True,
    },
    {
        "symbol": "MMM",
        "name": "3M Company",
        "market_cap_b": 90.9900,
        "country": "United States",
        "volume_m": 1.11,
        "options": True,
    },
    {
        "symbol": "MNST",
        "name": "Monster Beverage Corporation",
        "market_cap_b": 94.1000,
        "country": "United States",
        "volume_m": 2.91,
        "options": True,
    },
    {
        "symbol": "MO",
        "name": "Altria Group, Inc.",
        "market_cap_b": 113.7200,
        "country": "United States",
        "volume_m": 12.70,
        "options": True,
    },
    {
        "symbol": "MRK",
        "name": "Merck & Co., Inc.",
        "market_cap_b": 318.9400,
        "country": "United States",
        "volume_m": 3.09,
        "options": True,
    },
    {
        "symbol": "MRSH",
        "name": "Marsh & McLennan Companies, Inc.",
        "market_cap_b": 90.4400,
        "country": "United States",
        "volume_m": 1.44,
        "options": True,
    },
    {
        "symbol": "MRVL",
        "name": "Marvell Technology, Inc.",
        "market_cap_b": 159.1900,
        "country": "United States",
        "volume_m": 15.98,
        "options": True,
    },
    {
        "symbol": "MS",
        "name": "Morgan Stanley",
        "market_cap_b": 330.4200,
        "country": "United States",
        "volume_m": 3.13,
        "options": True,
    },
    {
        "symbol": "MSFT",
        "name": "Microsoft Corporation",
        "market_cap_b": 3380.0000,
        "country": "United States",
        "volume_m": 77.68,
        "options": True,
    },
    {
        "symbol": "MU",
        "name": "Micron Technology, Inc.",
        "market_cap_b": 985.9400,
        "country": "United States",
        "volume_m": 42.24,
        "options": True,
    },
    {
        "symbol": "NDAQ",
        "name": "Nasdaq, Inc.",
        "market_cap_b": 53.1200,
        "country": "United States",
        "volume_m": 1.52,
        "options": True,
    },
    {
        "symbol": "NEE",
        "name": "NextEra Energy, Inc.",
        "market_cap_b": 182.3600,
        "country": "United States",
        "volume_m": 4.48,
        "options": True,
    },
    {
        "symbol": "NEM",
        "name": "Newmont Corporation",
        "market_cap_b": 99.8700,
        "country": "United States",
        "volume_m": 3.36,
        "options": True,
    },
    {
        "symbol": "NET",
        "name": "Cloudflare, Inc.",
        "market_cap_b": 100.5900,
        "country": "United States",
        "volume_m": 1.65,
        "options": True,
    },
    {
        "symbol": "NFLX",
        "name": "Netflix, Inc.",
        "market_cap_b": 303.4300,
        "country": "United States",
        "volume_m": 28.64,
        "options": True,
    },
    {
        "symbol": "NKE",
        "name": "NIKE, Inc.",
        "market_cap_b": 62.3800,
        "country": "United States",
        "volume_m": 10.10,
        "options": True,
    },
    {
        "symbol": "NOW",
        "name": "ServiceNow, Inc.",
        "market_cap_b": 113.4100,
        "country": "United States",
        "volume_m": 19.42,
        "options": True,
    },
    {
        "symbol": "NVDA",
        "name": "NVIDIA Corporation",
        "market_cap_b": 4690.0000,
        "country": "United States",
        "volume_m": 73.75,
        "options": True,
    },
    {
        "symbol": "O",
        "name": "Realty Income Corporation",
        "market_cap_b": 59.8000,
        "country": "United States",
        "volume_m": 2.89,
        "options": True,
    },
    {
        "symbol": "ORCL",
        "name": "Oracle Corporation",
        "market_cap_b": 364.6700,
        "country": "United States",
        "volume_m": 24.13,
        "options": True,
    },
    {
        "symbol": "ORLY",
        "name": "O'Reilly Automotive, Inc.",
        "market_cap_b": 71.3000,
        "country": "United States",
        "volume_m": 6.11,
        "options": True,
    },
    {
        "symbol": "OXY",
        "name": "Occidental Petroleum Corporation",
        "market_cap_b": 55.0600,
        "country": "United States",
        "volume_m": 2.68,
        "options": True,
    },
    {
        "symbol": "PANW",
        "name": "Palo Alto Networks, Inc.",
        "market_cap_b": 261.7000,
        "country": "United States",
        "volume_m": 3.66,
        "options": True,
    },
    {
        "symbol": "PCAR",
        "name": "PACCAR Inc",
        "market_cap_b": 69.8600,
        "country": "United States",
        "volume_m": 1.60,
        "options": True,
    },
    {
        "symbol": "PEP",
        "name": "PepsiCo, Inc.",
        "market_cap_b": 190.8300,
        "country": "United States",
        "volume_m": 3.73,
        "options": True,
    },
    {
        "symbol": "PFE",
        "name": "Pfizer Inc.",
        "market_cap_b": 141.3200,
        "country": "United States",
        "volume_m": 24.79,
        "options": True,
    },
    {
        "symbol": "PG",
        "name": "The Procter & Gamble Company",
        "market_cap_b": 333.6200,
        "country": "United States",
        "volume_m": 5.04,
        "options": True,
    },
    {
        "symbol": "PGR",
        "name": "The Progressive Corporation",
        "market_cap_b": 123.5800,
        "country": "United States",
        "volume_m": 1.15,
        "options": True,
    },
    {
        "symbol": "PLD",
        "name": "Prologis, Inc.",
        "market_cap_b": 138.4900,
        "country": "United States",
        "volume_m": 1.49,
        "options": True,
    },
    {
        "symbol": "PLTR",
        "name": "Palantir Technologies Inc.",
        "market_cap_b": 292.7400,
        "country": "United States",
        "volume_m": 14.26,
        "options": True,
    },
    {
        "symbol": "PM",
        "name": "Philip Morris International Inc.",
        "market_cap_b": 299.7800,
        "country": "United States",
        "volume_m": 2.71,
        "options": True,
    },
    {
        "symbol": "PWR",
        "name": "Quanta Services, Inc.",
        "market_cap_b": 96.6000,
        "country": "United States",
        "volume_m": 1.55,
        "options": True,
    },
    {
        "symbol": "QCOM",
        "name": "QUALCOMM Incorporated",
        "market_cap_b": 162.8600,
        "country": "United States",
        "volume_m": 13.75,
        "options": True,
    },
    {
        "symbol": "RCL",
        "name": "Royal Caribbean Cruises Ltd.",
        "market_cap_b": 86.2600,
        "country": "United States",
        "volume_m": 1.03,
        "options": True,
    },
    {
        "symbol": "RTX",
        "name": "RTX Corporation",
        "market_cap_b": 285.0500,
        "country": "United States",
        "volume_m": 2.35,
        "options": True,
    },
    {
        "symbol": "SBUX",
        "name": "Starbucks Corporation",
        "market_cap_b": 122.3600,
        "country": "United States",
        "volume_m": 13.30,
        "options": True,
    },
    {
        "symbol": "SCHW",
        "name": "The Charles Schwab Corporation",
        "market_cap_b": 182.1000,
        "country": "United States",
        "volume_m": 2.38,
        "options": True,
    },
    {
        "symbol": "SLB",
        "name": "SLB N.V.",
        "market_cap_b": 72.4500,
        "country": "United States",
        "volume_m": 4.79,
        "options": True,
    },
    {
        "symbol": "SNDK",
        "name": "Sandisk Corporation",
        "market_cap_b": 187.1500,
        "country": "United States",
        "volume_m": 17.26,
        "options": True,
    },
    {
        "symbol": "SNOW",
        "name": "Snowflake Inc.",
        "market_cap_b": 102.4200,
        "country": "United States",
        "volume_m": 3.55,
        "options": True,
    },
    {
        "symbol": "SO",
        "name": "The Southern Company",
        "market_cap_b": 106.1000,
        "country": "United States",
        "volume_m": 3.18,
        "options": True,
    },
    {
        "symbol": "SPGI",
        "name": "S&P Global Inc.",
        "market_cap_b": 121.3300,
        "country": "United States",
        "volume_m": 1.37,
        "options": True,
    },
    {
        "symbol": "SRE",
        "name": "Sempra",
        "market_cap_b": 58.2100,
        "country": "United States",
        "volume_m": 1.02,
        "options": True,
    },
    {
        "symbol": "SYK",
        "name": "Stryker Corporation",
        "market_cap_b": 133.0300,
        "country": "United States",
        "volume_m": 1.04,
        "options": True,
    },
    {
        "symbol": "T",
        "name": "AT&T Inc.",
        "market_cap_b": 159.1500,
        "country": "United States",
        "volume_m": 27.10,
        "options": True,
    },
    {
        "symbol": "TER",
        "name": "Teradyne, Inc.",
        "market_cap_b": 56.7100,
        "country": "United States",
        "volume_m": 3.42,
        "options": True,
    },
    {
        "symbol": "TFC",
        "name": "Truist Financial Corporation",
        "market_cap_b": 63.5600,
        "country": "United States",
        "volume_m": 3.92,
        "options": True,
    },
    {
        "symbol": "TGT",
        "name": "Target Corporation",
        "market_cap_b": 65.3000,
        "country": "United States",
        "volume_m": 1.08,
        "options": True,
    },
    {
        "symbol": "TJX",
        "name": "The TJX Companies, Inc.",
        "market_cap_b": 175.0000,
        "country": "United States",
        "volume_m": 1.74,
        "options": True,
    },
    {
        "symbol": "TMUS",
        "name": "T-Mobile US, Inc.",
        "market_cap_b": 186.6300,
        "country": "United States",
        "volume_m": 2.49,
        "options": True,
    },
    {
        "symbol": "TRV",
        "name": "The Travelers Companies, Inc.",
        "market_cap_b": 77.4800,
        "country": "United States",
        "volume_m": 1.27,
        "options": True,
    },
    {
        "symbol": "TSLA",
        "name": "Tesla, Inc.",
        "market_cap_b": 1210.0000,
        "country": "United States",
        "volume_m": 23.02,
        "options": True,
    },
    {
        "symbol": "TXN",
        "name": "Texas Instruments Incorporated",
        "market_cap_b": 257.0900,
        "country": "United States",
        "volume_m": 3.48,
        "options": True,
    },
    {
        "symbol": "UBER",
        "name": "Uber Technologies, Inc.",
        "market_cap_b": 141.1300,
        "country": "United States",
        "volume_m": 7.50,
        "options": True,
    },
    {
        "symbol": "UNH",
        "name": "UnitedHealth Group Incorporated",
        "market_cap_b": 386.8700,
        "country": "United States",
        "volume_m": 1.67,
        "options": True,
    },
    {
        "symbol": "UNP",
        "name": "Union Pacific Corporation",
        "market_cap_b": 170.4200,
        "country": "United States",
        "volume_m": 1.76,
        "options": True,
    },
    {
        "symbol": "UPS",
        "name": "United Parcel Service, Inc.",
        "market_cap_b": 87.6700,
        "country": "United States",
        "volume_m": 2.21,
        "options": True,
    },
    {
        "symbol": "USB",
        "name": "U.S. Bancorp",
        "market_cap_b": 98.2100,
        "country": "United States",
        "volume_m": 2.39,
        "options": True,
    },
    {
        "symbol": "V",
        "name": "Visa Inc.",
        "market_cap_b": 668.6900,
        "country": "United States",
        "volume_m": 4.44,
        "options": True,
    },
    {
        "symbol": "VLO",
        "name": "Valero Energy Corporation",
        "market_cap_b": 91.7300,
        "country": "United States",
        "volume_m": 1.13,
        "options": True,
    },
    {
        "symbol": "VRT",
        "name": "Vertiv Holdings Co",
        "market_cap_b": 87.2700,
        "country": "United States",
        "volume_m": 8.86,
        "options": True,
    },
    {
        "symbol": "VST",
        "name": "Vistra Corp.",
        "market_cap_b": 50.1000,
        "country": "United States",
        "volume_m": 2.18,
        "options": True,
    },
    {
        "symbol": "VZ",
        "name": "Verizon Communications Inc.",
        "market_cap_b": 191.0700,
        "country": "United States",
        "volume_m": 10.62,
        "options": True,
    },
    {
        "symbol": "WBD",
        "name": "Warner Bros. Discovery, Inc.",
        "market_cap_b": 63.9700,
        "country": "United States",
        "volume_m": 6.96,
        "options": True,
    },
    {
        "symbol": "WDC",
        "name": "Western Digital Corporation",
        "market_cap_b": 182.8200,
        "country": "United States",
        "volume_m": 5.74,
        "options": True,
    },
    {
        "symbol": "WELL",
        "name": "Welltower Inc.",
        "market_cap_b": 170.6300,
        "country": "United States",
        "volume_m": 1.12,
        "options": True,
    },
    {
        "symbol": "WFC",
        "name": "Wells Fargo & Company",
        "market_cap_b": 258.4300,
        "country": "United States",
        "volume_m": 5.09,
        "options": True,
    },
    {
        "symbol": "WM",
        "name": "Waste Management, Inc.",
        "market_cap_b": 90.8400,
        "country": "United States",
        "volume_m": 1.29,
        "options": True,
    },
    {
        "symbol": "WMB",
        "name": "The Williams Companies, Inc.",
        "market_cap_b": 85.8500,
        "country": "United States",
        "volume_m": 2.48,
        "options": True,
    },
    {
        "symbol": "WMT",
        "name": "Walmart Inc.",
        "market_cap_b": 880.5600,
        "country": "United States",
        "volume_m": 13.20,
        "options": True,
    },
    {
        "symbol": "XOM",
        "name": "ExxonMobil Holdings Corporation",
        "market_cap_b": 647.1600,
        "country": "United States",
        "volume_m": 4.57,
        "options": True,
    },
]


# Convenience lookup by symbol
STOCKS_BY_SYMBOL = {stock["symbol"]: stock for stock in STOCKS}
