"""
ETF market data configuration.

- market_cap_b: Market capitalization (net assets) in billions of USD (4 decimal places)
- volume_m: Trading volume in millions of shares (2 decimal places)
- options: Whether options are available for this symbol

Sorted alphabetically by symbol. Duplicate symbols removed.
Same structure as the stock dataset so both files can be iterated on identically.
Inverse/short/bear-type and bond/fixed-income ETFs excluded (bull/long
equity, commodity, and non-directional equity funds only).
"""

ETFS = [
    {
        "symbol": "AAPU",
        "name": "Direxion Daily AAPL Bull 2X ETF",
        "market_cap_b": 0.1919,
        "country": "United States",
        "volume_m": 1.44,
        "options": True,
    },
    {
        "symbol": "AMDL",
        "name": "GraniteShares 2x Long AMD Daily ETF",
        "market_cap_b": 1.0300,
        "country": "United States",
        "volume_m": 3.04,
        "options": True,
    },
    {
        "symbol": "AMZU",
        "name": "Direxion Daily AMZN Bull 2X ETF",
        "market_cap_b": 0.2789,
        "country": "United States",
        "volume_m": 2.85,
        "options": True,
    },
    {
        "symbol": "BIZD",
        "name": "VanEck BDC Income ETF",
        "market_cap_b": 1.5800,
        "country": "United States",
        "volume_m": 2.27,
        "options": True,
    },
    {
        "symbol": "CGDV",
        "name": "Capital Group Dividend Value ETF",
        "market_cap_b": 36.9700,
        "country": "United States",
        "volume_m": 2.83,
        "options": True,
    },
    {
        "symbol": "CGGR",
        "name": "Capital Group Growth ETF",
        "market_cap_b": 23.9800,
        "country": "United States",
        "volume_m": 1.88,
        "options": True,
    },
    {
        "symbol": "CONL",
        "name": "GraniteShares 2x Long COIN Daily ETF",
        "market_cap_b": 0.5226,
        "country": "United States",
        "volume_m": 9.56,
        "options": True,
    },
    {
        "symbol": "DFAR",
        "name": "Dimensional US Real Estate ETF",
        "market_cap_b": 1.8200,
        "country": "United States",
        "volume_m": 2.00,
        "options": True,
    },
    {
        "symbol": "DGRO",
        "name": "iShares Core Dividend Growth ETF",
        "market_cap_b": 42.2400,
        "country": "United States",
        "volume_m": 1.04,
        "options": True,
    },
    {
        "symbol": "DIA",
        "name": "State Street SPDR Dow Jones Industrial Average ETF Trust",
        "market_cap_b": 45.0800,
        "country": "United States",
        "volume_m": 1.91,
        "options": True,
    },
    {
        "symbol": "DYNF",
        "name": "iShares U.S. Equity Factor Rotation Active ETF",
        "market_cap_b": 37.5000,
        "country": "United States",
        "volume_m": 1.03,
        "options": True,
    },
    {
        "symbol": "FBL",
        "name": "GraniteShares 2x Long META Daily ETF",
        "market_cap_b": 0.1754,
        "country": "United States",
        "volume_m": 2.79,
        "options": True,
    },
    {
        "symbol": "FNDX",
        "name": "Schwab Fundamental U.S. Large Company ETF",
        "market_cap_b": 26.3900,
        "country": "United States",
        "volume_m": 1.74,
        "options": True,
    },
    {
        "symbol": "GPIQ",
        "name": "Goldman Sachs Nasdaq-100 Premium Income ETF",
        "market_cap_b": 4.9800,
        "country": "United States",
        "volume_m": 1.14,
        "options": True,
    },
    {
        "symbol": "HDV",
        "name": "iShares Core High Dividend ETF",
        "market_cap_b": 14.3700,
        "country": "United States",
        "volume_m": 4.38,
        "options": True,
    },
    {
        "symbol": "IGV",
        "name": "iShares Expanded Tech-Software Sector ETF",
        "market_cap_b": 11.7100,
        "country": "United States",
        "volume_m": 8.91,
        "options": True,
    },
    {
        "symbol": "IHI",
        "name": "iShares U.S. Medical Devices ETF",
        "market_cap_b": 2.9400,
        "country": "United States",
        "volume_m": 1.74,
        "options": True,
    },
    {
        "symbol": "IJH",
        "name": "iShares Core S&P Mid-Cap ETF",
        "market_cap_b": 122.1400,
        "country": "United States",
        "volume_m": 3.20,
        "options": True,
    },
    {
        "symbol": "IJR",
        "name": "iShares Core S&P Small Cap ETF",
        "market_cap_b": 109.0400,
        "country": "United States",
        "volume_m": 1.12,
        "options": True,
    },
    {
        "symbol": "IVV",
        "name": "iShares Core S&P 500 ETF",
        "market_cap_b": 868.2900,
        "country": "United States",
        "volume_m": 2.15,
        "options": True,
    },
    {
        "symbol": "IWD",
        "name": "iShares Russell 1000 Value ETF",
        "market_cap_b": 80.3300,
        "country": "United States",
        "volume_m": 1.05,
        "options": True,
    },
    {
        "symbol": "IWF",
        "name": "iShares Russell 1000 Growth ETF",
        "market_cap_b": 121.4100,
        "country": "United States",
        "volume_m": 2.21,
        "options": True,
    },
    {
        "symbol": "IWM",
        "name": "iShares Russell 2000 ETF",
        "market_cap_b": 80.0800,
        "country": "United States",
        "volume_m": 13.82,
        "options": True,
    },
    {
        "symbol": "IYR",
        "name": "iShares U.S. Real Estate ETF",
        "market_cap_b": 4.6400,
        "country": "United States",
        "volume_m": 3.82,
        "options": True,
    },
    {
        "symbol": "JEPI",
        "name": "JPMorgan Equity Premium Income ETF",
        "market_cap_b": 45.3400,
        "country": "United States",
        "volume_m": 2.71,
        "options": True,
    },
    {
        "symbol": "JEPQ",
        "name": "JPMorgan NASDAQ Equity Premium Income ETF",
        "market_cap_b": 38.8600,
        "country": "United States",
        "volume_m": 4.84,
        "options": True,
    },
    {
        "symbol": "KBWB",
        "name": "Invesco KBW Bank ETF",
        "market_cap_b": 6.7600,
        "country": "United States",
        "volume_m": 1.17,
        "options": True,
    },
    {
        "symbol": "KRE",
        "name": "State Street SPDR S&P Regional Banking ETF",
        "market_cap_b": 4.4500,
        "country": "United States",
        "volume_m": 4.93,
        "options": True,
    },
    {
        "symbol": "MAGS",
        "name": "Roundhill Magnificent Seven ETF",
        "market_cap_b": 3.6700,
        "country": "United States",
        "volume_m": 1.97,
        "options": True,
    },
    {
        "symbol": "METU",
        "name": "Direxion Daily META Bull 2X ETF",
        "market_cap_b": 0.3827,
        "country": "United States",
        "volume_m": 10.55,
        "options": True,
    },
    {
        "symbol": "MSFL",
        "name": "GraniteShares 2x Long MSFT Daily ETF",
        "market_cap_b": 0.1228,
        "country": "United States",
        "volume_m": 6.21,
        "options": True,
    },
    {
        "symbol": "MSFU",
        "name": "Direxion Daily MSFT Bull 2X ETF",
        "market_cap_b": 0.7902,
        "country": "United States",
        "volume_m": 19.22,
        "options": True,
    },
    {
        "symbol": "MSOS",
        "name": "AdvisorShares Pure US Cannabis ETF",
        "market_cap_b": 0.8213,
        "country": "United States",
        "volume_m": 2.22,
        "options": True,
    },
    {
        "symbol": "MSTU",
        "name": "T-Rex 2X Long MSTR Daily Target ETF",
        "market_cap_b": 0.3629,
        "country": "United States",
        "volume_m": 62.10,
        "options": True,
    },
    {
        "symbol": "MTUM",
        "name": "iShares MSCI USA Momentum Factor ETF",
        "market_cap_b": 26.2100,
        "country": "United States",
        "volume_m": 1.34,
        "options": True,
    },
    {
        "symbol": "NAIL",
        "name": "Direxion Daily Homebuilders & Supplies Bull 3X ETF",
        "market_cap_b": 0.5408,
        "country": "United States",
        "volume_m": 1.17,
        "options": True,
    },
    {
        "symbol": "NOBL",
        "name": "ProShares S&P 500 Dividend Aristocrats ETF",
        "market_cap_b": 11.5000,
        "country": "United States",
        "volume_m": 1.06,
        "options": True,
    },
    {
        "symbol": "NVDL",
        "name": "GraniteShares 2x Long NVDA Daily ETF",
        "market_cap_b": 3.1900,
        "country": "United States",
        "volume_m": 7.48,
        "options": True,
    },
    {
        "symbol": "NVDX",
        "name": "T-Rex 2X Long NVIDIA Daily Target ETF",
        "market_cap_b": 0.4035,
        "country": "United States",
        "volume_m": 5.62,
        "options": True,
    },
    {
        "symbol": "NVDY",
        "name": "YieldMax NVDA Option Income Strategy ETF",
        "market_cap_b": 1.3400,
        "country": "United States",
        "volume_m": 1.26,
        "options": True,
    },
    {
        "symbol": "QQQI",
        "name": "NEOS Nasdaq 100 High Income ETF",
        "market_cap_b": 13.3100,
        "country": "United States",
        "volume_m": 3.69,
        "options": True,
    },
    {
        "symbol": "QQQM",
        "name": "Invesco NASDAQ 100 ETF",
        "market_cap_b": 95.2800,
        "country": "United States",
        "volume_m": 2.52,
        "options": True,
    },
    {
        "symbol": "QYLD",
        "name": "Global X NASDAQ 100 Covered Call ETF",
        "market_cap_b": 8.0700,
        "country": "United States",
        "volume_m": 3.44,
        "options": True,
    },
    {
        "symbol": "RSP",
        "name": "Invesco S&P 500 Equal Weight ETF",
        "market_cap_b": 95.9100,
        "country": "United States",
        "volume_m": 9.59,
        "options": True,
    },
    {
        "symbol": "SCHA",
        "name": "Schwab U.S. Small-Cap ETF",
        "market_cap_b": 22.7000,
        "country": "United States",
        "volume_m": 1.18,
        "options": True,
    },
    {
        "symbol": "SCHB",
        "name": "Schwab U.S. Broad Market ETF",
        "market_cap_b": 42.7800,
        "country": "United States",
        "volume_m": 4.05,
        "options": True,
    },
    {
        "symbol": "SCHD",
        "name": "Schwab US Dividend Equity ETF",
        "market_cap_b": 100.8900,
        "country": "United States",
        "volume_m": 24.50,
        "options": True,
    },
    {
        "symbol": "SCHG",
        "name": "Schwab U.S. Large-Cap Growth ETF",
        "market_cap_b": 58.4700,
        "country": "United States",
        "volume_m": 4.49,
        "options": True,
    },
    {
        "symbol": "SCHH",
        "name": "Schwab U.S. REIT ETF",
        "market_cap_b": 11.4900,
        "country": "United States",
        "volume_m": 3.31,
        "options": True,
    },
    {
        "symbol": "SCHV",
        "name": "Schwab U.S. Large-Cap Value ETF",
        "market_cap_b": 15.7900,
        "country": "United States",
        "volume_m": 1.93,
        "options": True,
    },
    {
        "symbol": "SCHX",
        "name": "Schwab U.S. Large-Cap ETF",
        "market_cap_b": 70.9400,
        "country": "United States",
        "volume_m": 5.33,
        "options": True,
    },
    {
        "symbol": "SMH",
        "name": "VanEck Semiconductor ETF",
        "market_cap_b": 69.7800,
        "country": "United States",
        "volume_m": 9.65,
        "options": True,
    },
    {
        "symbol": "SOXL",
        "name": "Direxion Daily Semiconductor Bull 3X ETF",
        "market_cap_b": 22.8700,
        "country": "United States",
        "volume_m": 77.59,
        "options": True,
    },
    {
        "symbol": "SOXQ",
        "name": "Invesco PHLX Semiconductor ETF",
        "market_cap_b": 2.4800,
        "country": "United States",
        "volume_m": 1.81,
        "options": True,
    },
    {
        "symbol": "SOXX",
        "name": "iShares Semiconductor ETF",
        "market_cap_b": 45.5500,
        "country": "United States",
        "volume_m": 11.97,
        "options": True,
    },
    {
        "symbol": "SPLV",
        "name": "Invesco S&P 500 Low Volatility ETF",
        "market_cap_b": 7.1300,
        "country": "United States",
        "volume_m": 1.88,
        "options": True,
    },
    {
        "symbol": "SPMO",
        "name": "Invesco S&P 500 Momentum ETF",
        "market_cap_b": 21.6900,
        "country": "United States",
        "volume_m": 1.46,
        "options": True,
    },
    {
        "symbol": "SPSM",
        "name": "State Street SPDR Portfolio S&P 600 Small Cap ETF",
        "market_cap_b": 17.2100,
        "country": "United States",
        "volume_m": 1.04,
        "options": True,
    },
    {
        "symbol": "SPXL",
        "name": "Direxion Daily S&P 500 Bull 3X ETF",
        "market_cap_b": 6.5200,
        "country": "United States",
        "volume_m": 1.36,
        "options": True,
    },
    {
        "symbol": "SPY",
        "name": "State Street SPDR S&P 500 ETF",
        "market_cap_b": 780.7100,
        "country": "United States",
        "volume_m": 31.11,
        "options": True,
    },
    {
        "symbol": "SPYD",
        "name": "State Street SPDR Portfolio S&P 500 High Dividend ETF",
        "market_cap_b": 7.5500,
        "country": "United States",
        "volume_m": 1.07,
        "options": True,
    },
    {
        "symbol": "SPYG",
        "name": "State Street SPDR Portfolio S&P 500 Growth ETF",
        "market_cap_b": 51.0700,
        "country": "United States",
        "volume_m": 4.80,
        "options": True,
    },
    {
        "symbol": "SPYI",
        "name": "NEOS S&P 500 High Income ETF",
        "market_cap_b": 10.8500,
        "country": "United States",
        "volume_m": 1.91,
        "options": True,
    },
    {
        "symbol": "SPYM",
        "name": "State Street SPDR Portfolio S&P 500 ETF",
        "market_cap_b": 157.4100,
        "country": "United States",
        "volume_m": 5.87,
        "options": True,
    },
    {
        "symbol": "SPYV",
        "name": "State Street SPDR Portfolio S&P 500 Value ETF",
        "market_cap_b": 35.7200,
        "country": "United States",
        "volume_m": 1.07,
        "options": True,
    },
    {
        "symbol": "SSO",
        "name": "ProShares Ultra S&P 500",
        "market_cap_b": 7.7100,
        "country": "United States",
        "volume_m": 1.65,
        "options": True,
    },
    {
        "symbol": "TNA",
        "name": "Direxion Daily Small Cap Bull 3X ETF",
        "market_cap_b": 1.3200,
        "country": "United States",
        "volume_m": 3.23,
        "options": True,
    },
    {
        "symbol": "TSLL",
        "name": "Direxion Daily TSLA Bull 2X ETF",
        "market_cap_b": 3.0000,
        "country": "United States",
        "volume_m": 60.87,
        "options": True,
    },
    {
        "symbol": "TSLT",
        "name": "T-REX 2X Long Tesla Daily Target ETF",
        "market_cap_b": 0.1183,
        "country": "United States",
        "volume_m": 2.23,
        "options": True,
    },
    {
        "symbol": "UDOW",
        "name": "ProShares UltraPro Dow30",
        "market_cap_b": 0.8011,
        "country": "United States",
        "volume_m": 1.51,
        "options": True,
    },
    {
        "symbol": "UNG",
        "name": "United States Natural Gas Fund LP",
        "market_cap_b": 0.4823,
        "country": "United States",
        "volume_m": 8.18,
        "options": True,
    },
    {
        "symbol": "UPRO",
        "name": "ProShares UltraPro S&P500",
        "market_cap_b": 5.0700,
        "country": "United States",
        "volume_m": 1.54,
        "options": True,
    },
    {
        "symbol": "USMV",
        "name": "iShares MSCI USA Min Vol Factor ETF",
        "market_cap_b": 23.0800,
        "country": "United States",
        "volume_m": 1.47,
        "options": True,
    },
    {
        "symbol": "USO",
        "name": "United States Oil Fund LP",
        "market_cap_b": 2.3300,
        "country": "United States",
        "volume_m": 2.63,
        "options": True,
    },
    {
        "symbol": "UUP",
        "name": "Invesco DB US Dollar Index Bullish Fund",
        "market_cap_b": 0.4298,
        "country": "United States",
        "volume_m": 1.72,
        "options": True,
    },
    {
        "symbol": "UVXY",
        "name": "ProShares Ultra VIX Short-Term Futures ETF",
        "market_cap_b": 0.2619,
        "country": "United States",
        "volume_m": 4.97,
        "options": True,
    },
    {
        "symbol": "VGT",
        "name": "Vanguard Information Technology ETF",
        "market_cap_b": 140.2600,
        "country": "United States",
        "volume_m": 2.78,
        "options": True,
    },
    {
        "symbol": "VIXY",
        "name": "ProShares VIX Short-Term Futures ETF",
        "market_cap_b": 0.2140,
        "country": "United States",
        "volume_m": 1.51,
        "options": True,
    },
    {
        "symbol": "VNQ",
        "name": "Vanguard Real Estate ETF",
        "market_cap_b": 39.1400,
        "country": "United States",
        "volume_m": 2.36,
        "options": True,
    },
    {
        "symbol": "VO",
        "name": "Vanguard Mid-Cap ETF",
        "market_cap_b": 105.0600,
        "country": "United States",
        "volume_m": 1.46,
        "options": True,
    },
    {
        "symbol": "VOO",
        "name": "Vanguard S&P 500 ETF",
        "market_cap_b": 980.3000,
        "country": "United States",
        "volume_m": 3.95,
        "options": True,
    },
    {
        "symbol": "VTI",
        "name": "Vanguard Total Stock Market ETF",
        "market_cap_b": 657.2500,
        "country": "United States",
        "volume_m": 1.95,
        "options": True,
    },
    {
        "symbol": "VTV",
        "name": "Vanguard Value ETF",
        "market_cap_b": 187.3400,
        "country": "United States",
        "volume_m": 1.58,
        "options": True,
    },
    {
        "symbol": "VUG",
        "name": "Vanguard Growth ETF",
        "market_cap_b": 216.1500,
        "country": "United States",
        "volume_m": 3.66,
        "options": True,
    },
    {
        "symbol": "VXX",
        "name": "iPath Series B S&P 500 VIX Short-Term Futures ETN",
        "market_cap_b": 0.4981,
        "country": "United States",
        "volume_m": 5.64,
        "options": True,
    },
    {
        "symbol": "VYM",
        "name": "Vanguard High Dividend Yield Index ETF",
        "market_cap_b": 81.0200,
        "country": "United States",
        "volume_m": 1.08,
        "options": True,
    },
    {
        "symbol": "XBI",
        "name": "State Street SPDR S&P Biotech ETF",
        "market_cap_b": 10.3100,
        "country": "United States",
        "volume_m": 3.40,
        "options": True,
    },
    {
        "symbol": "XHB",
        "name": "State Street SPDR S&P Homebuilders ETF",
        "market_cap_b": 1.6400,
        "country": "United States",
        "volume_m": 2.19,
        "options": True,
    },
    {
        "symbol": "XLB",
        "name": "State Street Materials Select Sector SPDR ETF",
        "market_cap_b": 8.4800,
        "country": "United States",
        "volume_m": 6.19,
        "options": True,
    },
    {
        "symbol": "XLC",
        "name": "State Street Communication Services Select Sector SPDR ETF",
        "market_cap_b": 22.1400,
        "country": "United States",
        "volume_m": 4.26,
        "options": True,
    },
    {
        "symbol": "XLE",
        "name": "State Street Energy Select Sector SPDR ETF",
        "market_cap_b": 39.5400,
        "country": "United States",
        "volume_m": 12.83,
        "options": True,
    },
    {
        "symbol": "XLF",
        "name": "State Street Financial Select Sector SPDR ETF",
        "market_cap_b": 55.6400,
        "country": "United States",
        "volume_m": 19.64,
        "options": True,
    },
    {
        "symbol": "XLI",
        "name": "State Street Industrial Select Sector SPDR ETF",
        "market_cap_b": 33.1900,
        "country": "United States",
        "volume_m": 3.92,
        "options": True,
    },
    {
        "symbol": "XLK",
        "name": "State Street Technology Select Sector SPDR ETF",
        "market_cap_b": 116.6500,
        "country": "United States",
        "volume_m": 9.10,
        "options": True,
    },
    {
        "symbol": "XLP",
        "name": "State Street Consumer Staples Select Sector SPDR ETF",
        "market_cap_b": 13.9300,
        "country": "United States",
        "volume_m": 10.33,
        "options": True,
    },
    {
        "symbol": "XLRE",
        "name": "State Street Real Estate Select Sector SPDR ETF",
        "market_cap_b": 8.5300,
        "country": "United States",
        "volume_m": 3.78,
        "options": True,
    },
    {
        "symbol": "XLU",
        "name": "State Street Utilities Select Sector SPDR ETF",
        "market_cap_b": 23.7700,
        "country": "United States",
        "volume_m": 13.17,
        "options": True,
    },
    {
        "symbol": "XLV",
        "name": "State Street Health Care Select Sector SPDR ETF",
        "market_cap_b": 41.6600,
        "country": "United States",
        "volume_m": 8.16,
        "options": True,
    },
    {
        "symbol": "XLY",
        "name": "State Street Consumer Discretionary Select Sector SPDR ETF",
        "market_cap_b": 21.1900,
        "country": "United States",
        "volume_m": 4.92,
        "options": True,
    },
    {
        "symbol": "XME",
        "name": "State Street SPDR S&P Metals & Mining ETF",
        "market_cap_b": 3.9700,
        "country": "United States",
        "volume_m": 1.22,
        "options": True,
    },
    {
        "symbol": "XRT",
        "name": "State Street SPDR S&P Retail ETF",
        "market_cap_b": 0.4319,
        "country": "United States",
        "volume_m": 4.08,
        "options": True,
    },
]


# Convenience lookup by symbol
ETFS_BY_SYMBOL = {etf["symbol"]: etf for etf in ETFS}
